---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: assistance-job-01
  namespace: atendimento
  labels:
    service: cronjob
    environment: development
spec:
  schedule: "0 7 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 240
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
        environment: development
        spec:
          restartPolicy: "OnFailure"
          containers:
          - name: cronjob
            image: "341852639037.dkr.ecr.us-east-1.amazonaws.com/assistance-job:latest"
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: assistance-job-01
              - secretRef:
                  name: assistance-job-01