apiVersion: batch/v1
kind: CronJob
metadata:
  name: assistance-job-03
  namespace: atendimento
  labels:
    app.kubernetes.io/instance: assistance-job-03
    environment: development
    service: cronjob
  managedFields:
spec:
  jobTemplate:
    spec:
      template:
        service: cronjob
        spec:
          containers:
          - name: cronjob
            image: 341852639037.dkr.ecr.us-east-1.amazonaws.com/assistance-job:latest
            imagePullPolicy: IfNotPresent
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: OnFailure
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
  schedule: 0 7 * * *
  startingDeadlineSeconds: 240
  successfulJobsHistoryLimit: 3
  suspend: false