apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apresentacao
  namespace: argocd
spec:
  project: atendimento
  source:
    repoURL: git@github.com:ektopan/atendimento.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: atendimento
  syncPolicy:
    retry:
      limit: 2
    automated:
        prune: true
        selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true